### PR TITLE
IV length issue fixed

### PR DESCRIPTION
**Pull request by psturc**
### Motivation

https://stackoverflow.com/questions/42485408/getting-error-of-invalid-iv-length-while-using-aes-256-cbc-for-encryption-in-nod

### CODE REVIEW

**Comment by trepel** [comment]
@psturc I think @matzew is no PTO. We need to find out someone else to have a look.

**Comment by psturc** [comment]
@trepel good point, @wei-lee can you please take a look?

**Comment by trepel** [comment]
the modification was tested via https://github.com/feedhenry/testing-cloud-app deployed with both node4 and node6 runtimes. Works as expected.

**Comment by pb82** [comment]
LGTM, tests also passed

**Comment by wtrocki** [comment]
@psturc it looks like this PR broke raincatcher authentication. After using mbaas-api that contains this change I cannot login to portal and mobie. Using old version works fine.

**Pull request merged**
